import AdminLayout from '@/Layouts/AdminLayout';
import { Head, Link, router } from '@inertiajs/react';
import { nameOf } from './EntityFields';
import { useLanguage } from '@/i18n';

export default function EntityIndex({ items, resource, title, status = 'all' }) {
    const { locale, dir, t } = useLanguage();
    const isEvent = resource === 'events';
    const entity = isEvent ? t('addNewEvent') : t('addNewOrganization');
    const localizedTitle = isEvent ? t('eventsTitle') : t('organizationsTitle');
    const eventFilters = [['all', t('all')], ['upcoming', t('upcoming')], ['past', t('past')]];
    const eventDate = item => item.event_dates?.[0];
    return <AdminLayout header={<div className="flex items-center justify-between"><h1 className="font-serif text-3xl font-bold">{localizedTitle}</h1><Link className="rounded-xl bg-[#49351F] px-5 py-3 text-white" href={route(`admin.${resource}.create`)}>+ {entity}</Link></div>}>
        <Head title={title}/>{isEvent && <div className="mb-4 flex flex-wrap gap-2" role="group" aria-label={t('eventStatus')}>
            {eventFilters.map(([value, label]) => <Link key={value} href={route('admin.events.index', value === 'all' ? {} : { status: value })} preserveScroll className={`rounded-full border px-4 py-2 text-sm font-semibold transition-colors ${status === value ? 'border-[#49351F] bg-[#49351F] text-white' : 'border-[#98754d]/40 text-[#49351F] hover:bg-[#EED9AE]/50'}`}>{label}</Link>)}
        </div>}
        <div className="overflow-x-auto rounded-xl border"><table dir={dir} className="w-full text-start text-sm"><thead className="bg-stone-100"><tr><th className={`p-4 ${dir === 'rtl' ? 'text-right' : 'text-left'}`}>{t('name')}</th>{isEvent && <th className={dir === 'rtl' ? 'text-right' : 'text-left'}>{t('categories')}</th>}{isEvent ? <><th className={dir === 'rtl' ? 'text-right' : 'text-left'}>{t('organization')}</th><th className={dir === 'rtl' ? 'text-right' : 'text-left'}>{t('dateTime')}</th><th className={dir === 'rtl' ? 'text-right' : 'text-left'}>{t('eventStatus')}</th></> : <th className={dir === 'rtl' ? 'text-right' : 'text-left'}>{t('relationTitle')}</th>}<th className="p-4 text-end">{t('actions')}</th></tr></thead><tbody>{items.data.map(item => { const date = eventDate(item); return <tr key={item.id} className="border-t"><td className="p-4 font-semibold">{nameOf(item.name, locale)}</td>{isEvent && <td className="max-w-xs"><div className="flex flex-wrap gap-1.5">{item.categories?.length ? item.categories.map(category => <Link href={route('admin.categories.edit', category.id)} key={category.id} className="rounded-full bg-[#EED9AE]/60 px-2 py-1 text-xs hover:bg-[#D5B66F] hover:underline">{nameOf(category.name, locale)}</Link>) : <span className="text-[#44301D]/45">—</span>}</div></td>}{isEvent ? <><td>{nameOf(item.organization?.name, locale)}</td><td><div>{date?.date || '—'}</div><div className="text-xs text-[#44301D]/60">{date ? `${date.start_at} – ${date.end_at}` : '—'}</div></td><td><span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${item.status === 'upcoming' ? 'bg-emerald-100 text-emerald-800' : 'bg-stone-200 text-stone-700'}`}>{t(item.status)}</span></td></> : <td>{`${item.is_active ? t('active') : t('disabled')} · ${item.events_count} ${t('events')}`}</td>}<td className="p-4 text-end"><div className="flex items-center justify-end gap-4"><Link href={route(`admin.${resource}.edit`, item.id)}>{t('edit')}</Link><button className="text-red-700" onClick={() => { if (confirm(`${t('delete')} “${nameOf(item.name, locale)}”?`)) router.delete(route(`admin.${resource}.destroy`, item.id)); }}>{t('delete')}</button></div></td></tr>; })}</tbody></table>{items.data.length === 0 && <p className="p-8 text-center">{t('noRecords')}</p>}</div>
        <div className="mt-4 flex gap-2">{items.links.map((link, index) => link.url ? <Link key={index} href={link.url} className={`rounded border px-3 py-2 ${link.active ? 'bg-stone-200' : ''}`} dangerouslySetInnerHTML={{ __html: link.label }}/> : null)}</div>
    </AdminLayout>;
}
