import TranslatableFields from '@/Components/Admin/TranslatableFields';
import AdminLayout from '@/Layouts/AdminLayout';
import { Head, router, useForm } from '@inertiajs/react';
import { useState } from 'react';
import { useLanguage } from '@/i18n';

const blank = { name:{en:'',fr:'',ar:''}, code:'', cities:[] };
export default function Index({ locations }) {
    const { locale, t } = useLanguage();
    const displayName = (name) => name?.[locale] || name?.en || name?.fr || name?.ar || t('none');
    const [editing, setEditing] = useState(null);
    const [formOpen, setFormOpen] = useState(false);
    const form = useForm(blank);
    const open = (location = null) => { setEditing(location); setFormOpen(true); form.setData(location ? { name:location.name,code:location.code||'',cities:location.cities||[],_method:'put' } : blank); form.clearErrors(); };
    const close = () => { setFormOpen(false); setEditing(null); form.reset(); };
    const submit = (e) => { e.preventDefault(); form.post(editing ? route('admin.locations.update',editing.id) : route('admin.locations.store'), { onSuccess:close }); };
    const addCity = () => form.setData('cities',[...form.data.cities,{en:'',fr:'',ar:''}]);
    const updateCity = (index,key,value) => form.setData('cities',form.data.cities.map((city,i)=>i===index?{...city,[key]:value}:city));
    return <AdminLayout header={<div className="flex items-end justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#747A3C]">{t('mapData')}</p><h1 className="font-serif text-3xl font-bold">{t('statesCitiesTitle')}</h1><p className="mt-1 text-sm text-[#44301D]/60">{t('locationsHelp')}</p></div><button onClick={()=>open()} className="rounded-xl bg-[#49351F] px-4 py-2.5 text-sm font-semibold text-white">+ {t('addNewState')}</button></div>}>
        <Head title={t('statesCitiesTitle')}/>
        <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{locations.map((location)=><article key={location.id} className="rounded-2xl border border-[#9B7847]/25 bg-white p-5 shadow-sm"><div className="flex justify-between"><div><p className="font-serif text-xl font-bold">{displayName(location.name)}</p><p className="text-xs uppercase tracking-wider text-[#747A3C]">{location.code || t('noCode')} · {location.cities?.length || 0} {t('cities').toLowerCase()}</p></div><div><button onClick={()=>open(location)} className="mr-3 text-sm font-semibold text-[#747A3C]">{t('edit')}</button><button onClick={()=>window.confirm(t('deleteStateConfirm'))&&router.delete(route('admin.locations.destroy',location.id))} className="text-sm font-semibold text-red-700">{t('delete')}</button></div></div><div className="mt-4 flex flex-wrap gap-1.5">{location.cities?.map((city,i)=><span key={i} className="rounded-full bg-[#EED9AE]/55 px-2.5 py-1 text-xs">{displayName(city)}</span>)}</div></article>)}</div>
        {formOpen ? <div className="fixed inset-0 z-50 grid place-items-center bg-[#2e2015]/60 p-4" onMouseDown={(e)=>e.target===e.currentTarget&&close()}><form onSubmit={submit} className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-[#faf7ef] p-6 shadow-2xl"><div className="mb-5 flex justify-between"><h2 className="font-serif text-2xl font-bold">{editing?t('editState'):t('newState')}</h2><button type="button" onClick={close} className="text-2xl">×</button></div><div className="space-y-5"><TranslatableFields label={t('name')} value={form.data.name} onChange={(v)=>form.setData('name',v)} errors={form.errors} required/><label className="block"><span className="mb-1 block text-sm font-semibold">{t('stateCode')}</span><input value={form.data.code} onChange={(e)=>form.setData('code',e.target.value.toUpperCase())} className="w-full rounded-xl border-[#9B7847]/35" placeholder="TN-11"/></label><div><div className="mb-3 flex items-center justify-between"><h3 className="text-sm font-semibold">{t('cities')}</h3><button type="button" onClick={addCity} className="rounded-lg bg-[#EED9AE] px-3 py-1.5 text-xs font-semibold">+ {t('addCity')}</button></div>{form.data.cities.map((city,index)=><div key={index} className="mb-2 grid grid-cols-[1fr_1fr_1fr_auto] gap-2"><input placeholder="English" value={city.en||''} onChange={(e)=>updateCity(index,'en',e.target.value)} className="rounded-lg border-[#9B7847]/35 text-sm"/><input placeholder="Français" value={city.fr||''} onChange={(e)=>updateCity(index,'fr',e.target.value)} className="rounded-lg border-[#9B7847]/35 text-sm"/><input dir="rtl" placeholder="العربية" value={city.ar||''} onChange={(e)=>updateCity(index,'ar',e.target.value)} className="rounded-lg border-[#9B7847]/35 text-sm"/><button type="button" onClick={()=>form.setData('cities',form.data.cities.filter((_,i)=>i!==index))} className="px-2 text-red-700">×</button></div>)}</div></div><div className="mt-6 flex justify-end"><button disabled={form.processing} className="rounded-xl bg-[#49351F] px-6 py-2.5 text-sm font-semibold text-white">{t('save')} {t('statesCities').toLowerCase()}</button></div></form></div> : null}
    </AdminLayout>;
}
