import FileUpload from '@/Components/Admin/FileUpload';
import TunisiaMap from '@/Components/TunisiaMap';
import Modal from '@/Components/Modal';
import TranslatableFields from '@/Components/Admin/TranslatableFields';
import AdminLayout from '@/Layouts/AdminLayout';
import { Head, Link, useForm } from '@inertiajs/react';
import { useMemo, useState } from 'react';
import { extractGoogleMapsCoordinates } from '@/lib/googleMaps';

const displayName=(name)=>name?.en||name?.fr||name?.ar||'Untitled';
const slugify=(text)=>text?.toLowerCase().trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'';
const Field=({label,error,children,required})=><label className="block"><span className="mb-1.5 block text-sm font-semibold">{label}{required&&<span className="text-red-700"> *</span>}</span>{children}{error&&<span className="mt-1 block text-xs text-red-700">{error}</span>}</label>;
const inputClass='w-full rounded-xl border-[#9B7847]/35 bg-white text-sm focus:border-[#747A3C] focus:ring-[#747A3C]';

export default function Form({item,options}) {
    const form=useForm({name:item?.name||{en:'',fr:'',ar:''},short_description:item?.short_description||{en:'',fr:'',ar:''},url:item?.url||'',description:item?.description||{en:'',fr:'',ar:''},main_image:null,icon:null,pictures:[],video_files:[],video_urls:[''],audio_files:[],longitude:item?.longitude??'',latitude:item?.latitude??'',google_maps_url:item?.google_maps_url??'',category_ids:item?.categories?.map(x=>x.id)||[],type_ids:item?.types?.map(x=>x.id)||[],author_id:item?.author_id||'',people:item?.people||[],location_id:item?.location_id||'',city:item?.city||'',is_active:item?.is_active??true,release:item?.release||'',importance:item?.importance||'medium',_method:item?'put':'post'});
    const {data,setData,errors,processing}=form;
    const [mapOpen,setMapOpen]=useState(false),[urlEdited,setUrlEdited]=useState(Boolean(item?.url));
    const cities=useMemo(()=>options.locations.find(x=>String(x.id)===String(data.location_id))?.cities||[],[options.locations,data.location_id]);
    const toggle=(field,id)=>setData(field,data[field].includes(id)?data[field].filter(x=>x!==id):[...data[field],id]);
    const submit=(e)=>{e.preventDefault();form.post(item?route('admin.cultural-items.update',item.id):route('admin.cultural-items.store'),{forceFormData:true});};
    return <AdminLayout header={<div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#747A3C]">Cultural item editor</p><h1 className="font-serif text-3xl font-bold">{item?'Edit cultural item':'New cultural item'}</h1></div>}>
        <Head title={item?'Edit cultural item':'New cultural item'}/><form onSubmit={submit} className="mx-auto max-w-6xl space-y-6">
            {Object.keys(errors).length>0&&<div className="rounded-xl border border-red-300 bg-red-50 p-4 text-sm text-red-800">Please review the highlighted fields. {Object.values(errors)[0]}</div>}
            <Section title="Identity" note="Public, translatable information about this item."><TranslatableFields label="Name" value={data.name} onChange={(v)=>{setData(prev=>({...prev,name:v,url:urlEdited?prev.url:slugify(v.en||v.fr)}));}} errors={errors} required/><Field label="URL slug" error={errors.url} required><input value={data.url} onChange={(e)=>{setUrlEdited(true);setData('url',slugify(e.target.value));}} className={inputClass}/></Field><TranslatableFields label="Short description" value={data.short_description} onChange={(v)=>setData('short_description',v)} errors={errors} multiline required/><TranslatableFields label="Description" value={data.description} onChange={(v)=>setData('description',v)} errors={errors} multiline required/></Section>
            <Section title="Classification"><div className="grid gap-6 md:grid-cols-2"><CheckGroup label="Categories" items={options.categories} selected={data.category_ids} toggle={(id)=>toggle('category_ids',id)} error={errors.category_ids}/><CheckGroup label="Types" items={options.types} selected={data.type_ids} toggle={(id)=>toggle('type_ids',id)} error={errors.type_ids}/></div><div className="grid gap-5 md:grid-cols-3"><Field label="Author / artist"><select value={data.author_id} onChange={(e)=>setData('author_id',e.target.value)} className={inputClass}><option value="">None</option>{options.artists.map(x=><option key={x.id} value={x.id}>{displayName(x.name)}{x.profession?` — ${x.profession}`:''}</option>)}</select></Field><Field label="Release date or year"><input value={data.release} onChange={(e)=>setData('release',e.target.value)} className={inputClass} placeholder="e.g. 1850 or 2024-05-20"/></Field><Field label="Importance"><select value={data.importance} onChange={(e)=>setData('importance',e.target.value)} className={inputClass}><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></Field></div><label className="inline-flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={data.is_active} onChange={(e)=>setData('is_active',e.target.checked)} className="rounded border-[#9B7847] text-[#747A3C] focus:ring-[#747A3C]"/>Visible on the public map</label></Section>
            <Section title="Location" note="Choose the state and city, then select the exact marker position on the map."><div className="grid gap-5 md:grid-cols-2"><Field label="State"><select value={data.location_id} onChange={(e)=>setData(prev=>({...prev,location_id:e.target.value,city:''}))} className={inputClass}><option value="">Select state</option>{options.locations.map(x=><option key={x.id} value={x.id}>{displayName(x.name)}</option>)}</select></Field><Field label="City"><select value={data.city} onChange={(e)=>setData('city',e.target.value)} className={inputClass} disabled={!data.location_id}><option value="">Select city</option>{cities.map((x,i)=><option key={i} value={displayName(x)}>{displayName(x)}</option>)}</select></Field></div><div className="grid gap-4 md:grid-cols-3"><Field label="Google Maps URL (optional)" error={errors.google_maps_url}><input type="url" value={data.google_maps_url} onChange={e=>setData(prev=>({...prev,google_maps_url:e.target.value,...(extractGoogleMapsCoordinates(e.target.value)||{})}))} className={inputClass}/></Field><div className="md:col-span-2 flex flex-wrap items-center gap-3"><button type="button" onClick={()=>setMapOpen(true)} className="rounded-xl bg-[#747A3C] px-4 py-2.5 text-sm font-semibold text-white">⌖ {data.longitude!==''?'Change position':'Add position'}</button><span className="text-sm text-[#44301D]/60">{data.longitude!==''?`Latitude ${Number(data.latitude).toFixed(6)} · Longitude ${Number(data.longitude).toFixed(6)}`:'No map position selected'}</span>{(errors.longitude||errors.latitude)&&<span className="text-xs text-red-700">{errors.longitude||errors.latitude}</span>}</div></div></Section>
            <Section title="People" note="People related to this item and their role or relationship.">{data.people.map((person,index)=><div key={index} className="mb-2 grid grid-cols-[1fr_1fr_auto] gap-2"><input value={person.name} onChange={(e)=>setData('people',data.people.map((p,i)=>i===index?{...p,name:e.target.value}:p))} className={inputClass} placeholder="Name"/><input value={person.position||''} onChange={(e)=>setData('people',data.people.map((p,i)=>i===index?{...p,position:e.target.value}:p))} className={inputClass} placeholder="Position or relationship"/><button type="button" onClick={()=>setData('people',data.people.filter((_,i)=>i!==index))} className="px-3 text-red-700">×</button></div>)}<button type="button" onClick={()=>setData('people',[...data.people,{name:'',position:''}])} className="rounded-lg bg-[#EED9AE] px-3 py-2 text-xs font-semibold">+ Add person</button></Section>
            <Section title="Media"><div className="grid gap-4 md:grid-cols-2"><Upload label="Main image" required={!item} accept="image/*" multiple={false} current={item?.main_image} onFiles={(f)=>setData('main_image',f[0])} error={errors.main_image}/><Upload label="Map icon" accept="image/*" multiple={false} current={item?.icon} onFiles={(f)=>setData('icon',f[0])}/><Upload label="Pictures album" accept="image/*" multiple onFiles={(f)=>setData('pictures',f)} current={item?.pictures}/><Upload label="Audio (MP3/WAV)" accept="audio/*" multiple onFiles={(f)=>setData('audio_files',f)} current={item?.audio?.length?`${item.audio.length} existing files`:null}/><Upload label="Video files" accept="video/*" multiple onFiles={(f)=>setData('video_files',f)} current={item?.videos?.length?`${item.videos.length} existing videos/links`:null}/><div><p className="mb-2 text-sm font-semibold">Video URLs</p>{data.video_urls.map((url,index)=><div key={index} className="mb-2 flex gap-2"><input type="url" value={url} onChange={(e)=>setData('video_urls',data.video_urls.map((v,i)=>i===index?e.target.value:v))} className={inputClass} placeholder="https://…"/><button type="button" onClick={()=>setData('video_urls',data.video_urls.filter((_,i)=>i!==index))} className="px-2 text-red-700">×</button></div>)}<button type="button" onClick={()=>setData('video_urls',[...data.video_urls,''])} className="text-xs font-semibold text-[#747A3C]">+ Add URL</button></div></div></Section>
            <div className="flex justify-end gap-3"><Link href={route('admin.cultural-items.index')} className="rounded-xl border border-[#9B7847]/40 px-5 py-2.5 text-sm font-semibold">Cancel</Link><button disabled={processing} className="rounded-xl bg-[#49351F] px-6 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{processing?'Saving…':'Save cultural item'}</button></div>
        </form>{mapOpen&&<MapPicker x={data.longitude} y={data.latitude} onClose={()=>setMapOpen(false)} onChoose={(x,y)=>{setData(prev=>({...prev,longitude:x,latitude:y}));setMapOpen(false);}}/>}
    </AdminLayout>;
}

function Section({title,note,children}) { return <section className="space-y-5 rounded-2xl border border-[#9B7847]/25 bg-[#EED9AE]/15 p-5 sm:p-7"><div><h2 className="font-serif text-xl font-bold">{title}</h2>{note&&<p className="mt-1 text-xs text-[#44301D]/55">{note}</p>}</div>{children}</section> }
function CheckGroup({label,items,selected,toggle,error}) { return <fieldset><legend className="mb-2 text-sm font-semibold">{label}</legend><div className="max-h-44 space-y-1 overflow-y-auto rounded-xl border border-[#9B7847]/30 bg-white p-2">{items.map(x=><label key={x.id} className="flex cursor-pointer items-center gap-2 rounded-lg px-2 py-2 text-sm hover:bg-[#EED9AE]/35"><input type="checkbox" checked={selected.includes(x.id)} onChange={()=>toggle(x.id)} className="rounded text-[#747A3C] focus:ring-[#747A3C]"/>{displayName(x.name)}</label>)}{!items.length&&<p className="p-2 text-xs text-[#44301D]/50">Create {label.toLowerCase()} first.</p>}</div>{error&&<span className="text-xs text-red-700">{error}</span>}</fieldset> }
function Upload({ onFiles, ...props }) { return <FileUpload {...props} onChange={value => onFiles(props.multiple ? value : value ? [value] : [])} />; }
function MapPicker({x,y,onChoose,onClose}) {
    const [point, setPoint] = useState(x !== '' && y !== '' ? { longitude: Number(x), latitude: Number(y) } : null);
    return <Modal show onClose={onClose}>
        <div className="bg-[#f7ead0] p-4">
            <div className="mb-3 flex items-center justify-between">
                <div><h2 className="font-serif text-xl font-bold">Choose map position</h2><p className="text-xs">Zoom in, then click within Tunisia to place the marker.</p></div>
                <button type="button" onClick={onClose} aria-label="Close map picker" className="size-10 text-2xl">×</button>
            </div>
            <div className="h-[60dvh] min-h-72"><TunisiaMap point={point} onChoosePoint={setPoint} /></div>
            <div className="mt-4 flex items-center justify-between gap-3">
                <p className="text-xs" aria-live="polite">{point ? `Latitude ${point.latitude.toFixed(6)} · Longitude ${point.longitude.toFixed(6)}` : 'No map position selected'}</p>
                <button type="button" disabled={!point} onClick={() => onChoose(point.longitude, point.latitude)} className="rounded-xl bg-[#747A3C] px-4 py-2 text-sm text-white disabled:opacity-40">Use this location</button>
            </div>
        </div>
    </Modal>;
}
