import AdminLayout from '@/Layouts/AdminLayout';
import TranslatableFields from '@/Components/Admin/TranslatableFields';
import RichTextEditor from '@/Components/Admin/RichTextEditor';
import TunisiaMap from '@/Components/TunisiaMap';
import { Check, Errors, Field, Select, Upload, links, nameOf, mediaUrl, inputClass } from '@/Components/Admin/EntityFields';
import { Head, Link, useForm, usePage } from '@inertiajs/react';
import { extractGoogleMapsCoordinates } from '@/lib/googleMaps';
import { useLanguage } from '@/i18n';

const translations = value => typeof value === 'object' && value !== null ? value : { en: value || '', fr: '', ar: '' };

export default function Form({ item, organizations, categories, locations }) {
    const { auth } = usePage().props;
    const { locale, t } = useLanguage();
    const organizationLocked = auth.user.role === 'organizer';
    const { data, setData, post, errors, processing, transform } = useForm({
        name: item?.name || { en: '', fr: '', ar: '' }, main_image: null, organization_id: item?.organization_id ?? (organizations.length === 1 ? organizations[0].id : ''),
        google_maps_url: item?.google_maps_url ?? '', ...Object.fromEntries(['payment_link', 'latitude', 'longitude', 'state_id', 'city', 'place_name', ...links, 'other_link'].map(key => [key, item?.[key] ?? ''])), short_description: translations(item?.short_description), description: translations(item?.description),
        is_free: item?.is_free ?? true, price: item?.price ?? 0, category_ids: item?.categories?.map(c => String(c.id)) || [], tags_text: (item?.tags || []).join(', '),
        event_dates: item?.event_dates?.map(slot => ({ date: slot.date.slice(0, 10), start_at: slot.start_at.slice(0, 5), end_at: slot.end_at.slice(0, 5) })) || [{ date: '', start_at: '', end_at: '' }],
        pictures: [], existing_pictures: item?.pictures || [], existing_videos: item?.videos || [], video_files: [], video_urls_text: '', _method: item ? 'put' : 'post',
    });
    const title = item ? `${t('edit')} ${t('event')}` : t('addNewEvent');
    const changeDate = (index, key, value) => setData('event_dates', data.event_dates.map((slot, i) => i === index ? { ...slot, [key]: value } : slot));
    const submit = e => { e.preventDefault(); transform(({ tags_text, video_urls_text, ...rest }) => ({ ...rest, tags: tags_text.split(',').map(t => t.trim()).filter(Boolean), video_urls: video_urls_text.split('\n').map(v => v.trim()).filter(Boolean) })); post(route(item ? 'admin.events.update' : 'admin.events.store', item?.id), { forceFormData: true }); };
    return <AdminLayout header={<h1 className="font-serif text-3xl font-bold">{title}</h1>}><Head title={title}/>
        <form onSubmit={submit} className="mx-auto max-w-5xl space-y-6"><Errors errors={errors}/>
            <TranslatableFields field="name" label={t('name')} value={data.name} onChange={v => setData('name', v)} required/>
            <div className="grid gap-5 sm:grid-cols-2"><Select label={t('organization')} value={data.organization_id} options={organizations} onChange={v => setData('organization_id', v)} disabled={organizationLocked}/><Upload label={t('mainImage')} current={item?.main_image} onChange={v => setData('main_image', v)}/></div>
            {!organizations.length && <p className="text-amber-800">{t('organizations')} {t('none').toLowerCase()}. <Link className="underline" href={route('admin.organizations.create')}>{t('addNewOrganization')}</Link></p>}
            <fieldset className="rounded-xl border p-4"><legend className="font-semibold">{t('categoriesLabel')}</legend><div className="flex flex-wrap gap-4">{categories.map(category => <label key={category.id} className="flex items-center gap-2"><input type="checkbox" checked={data.category_ids.includes(String(category.id))} onChange={e => setData('category_ids', e.target.checked ? [...data.category_ids, String(category.id)] : data.category_ids.filter(id => id !== String(category.id)))}/><span className="size-3 rounded-full" style={{ backgroundColor: category.color }}/>{nameOf(category.name, locale)}</label>)}</div></fieldset>
            <Field label={t('tags')} value={data.tags_text} onChange={v => setData('tags_text', v)}/>
            <section className="space-y-3 rounded-xl border p-4"><h2 className="font-serif text-xl font-bold">{t('eventDates')}</h2><p className="text-xs">{t('calendarDescription')}</p>{data.event_dates.map((slot, index) => <div key={index} className="grid items-end gap-3 sm:grid-cols-4"><Field label={t('date')} type="date" required value={slot.date} onChange={v => changeDate(index, 'date', v)}/><Field label={t('startsAt')} type="time" required value={slot.start_at} onChange={v => changeDate(index, 'start_at', v)}/><Field label={t('endsAt')} type="time" required value={slot.end_at} onChange={v => changeDate(index, 'end_at', v)}/><button type="button" disabled={data.event_dates.length === 1} className="p-2 text-red-700 disabled:opacity-30" onClick={() => setData('event_dates', data.event_dates.filter((_, i) => i !== index))}>{t('removeDate')}</button></div>)}<button type="button" className="rounded border px-4 py-2" onClick={() => setData('event_dates', [...data.event_dates, { date: '', start_at: '', end_at: '' }])}>{t('addDate')}</button></section>
            <Check label={t('freeEvent')} value={data.is_free} onChange={v => setData('is_free', v)}/><div className="grid gap-5 sm:grid-cols-2"><Field label={`${t('price')} (TND)`} type="number" min="0" step="0.01" disabled={data.is_free} value={data.price} onChange={v => setData('price', v)}/><Field label={t('paymentLink')} type="url" value={data.payment_link} onChange={v => setData('payment_link', v)}/></div>
            <TranslatableFields field="short_description" label={t('shortDescription')} value={data.short_description} onChange={v => setData('short_description', v)} multiline required/><TranslatableFields field="description" label={t('description')} value={data.description} onChange={v => setData('description', v)} multiline required/>
            <div className="grid gap-5 sm:grid-cols-3"><Select label="Event state" value={data.state_id} options={locations} onChange={v => setData('state_id', v)}/><Field label="City" required value={data.city} onChange={v => setData('city', v)}/><Field label="Place name" required value={data.place_name} onChange={v => setData('place_name', v)}/></div>
            <p className="text-sm">Click the map to place this event, or enter its coordinates.</p><div className="h-96 overflow-hidden rounded-xl border"><TunisiaMap point={{ latitude: data.latitude, longitude: data.longitude }} onChoosePoint={point => setData(current => ({ ...current, ...point }))}/></div>
            <div className="grid gap-5 sm:grid-cols-3"><Field label="Google Maps URL (optional)" type="url" value={data.google_maps_url} error={errors.google_maps_url} onChange={v => setData(current => ({ ...current, google_maps_url: v, ...(extractGoogleMapsCoordinates(v) || {}) }))}/><Field label="Latitude" type="number" min="-90" max="90" step="any" required value={data.latitude} onChange={v => setData('latitude', v)}/><Field label="Longitude" type="number" min="-180" max="180" step="any" required value={data.longitude} onChange={v => setData('longitude', v)}/></div>
            <section className="space-y-4 rounded-xl border p-4"><h2 className="font-serif text-xl font-bold">Media</h2><Upload label="Add pictures" multiple onChange={v => setData('pictures', v)}/><div className="flex flex-wrap gap-3">{data.existing_pictures.map(path => <div key={path}><img src={mediaUrl(path)} alt="Event gallery" className="h-24 w-32 rounded object-cover"/><button type="button" className="text-sm text-red-700" onClick={() => setData('existing_pictures', data.existing_pictures.filter(p => p !== path))}>Remove picture</button></div>)}</div><Upload label="Add video files" multiple accept="video/mp4,video/webm,video/quicktime" onChange={v => setData('video_files', v)}/>{data.existing_videos.map(path => <div key={path} className="flex gap-3 text-sm"><a href={mediaUrl(path)} target="_blank" rel="noreferrer" className="truncate underline">{path}</a><button type="button" className="text-red-700" onClick={() => setData('existing_videos', data.existing_videos.filter(p => p !== path))}>Remove video</button></div>)}<label className="block text-sm font-semibold">Add video links (one per line)<textarea rows="3" className={inputClass} value={data.video_urls_text} onChange={e => setData('video_urls_text', e.target.value)}/></label></section>
            <div className="grid gap-5 sm:grid-cols-2">{[...links, 'other_link'].map(key => <Field key={key} label={`${key.replace('_', ' ')} (optional)`} type="url" value={data[key]} onChange={v => setData(key, v)}/>)}</div>
            <div className="flex justify-end gap-4"><Link href={route('admin.events.index')} className="p-3">Cancel</Link><button disabled={processing} className="rounded-xl bg-[#49351F] px-6 py-3 text-white disabled:opacity-50">{processing ? 'Saving…' : 'Save event'}</button></div>
        </form>
    </AdminLayout>;
}
